### ISSUE TITLE
Support compact representation of in-place expanding text

### ISSUE THREAD

**Issue by lizadaly** [lizadaly/windrift#13]
See discussion below.

**Comment by michelleful** [comment]
Having the ability to nest expansions in other expansions would be useful. The (non-IF) context I'm thinking of is simplifying sentences and being able to progressively expand them so that a language learner/new reader can (a) not be overwhelmed by initial complexity and (b) get cued to the structure of a sentence. For example:

[The economy]() [grew](), [*]().
The world's largest economy [grew](), [*]().
The world's largest economy grew at [a rate]() of 2.9%, [*]().
The world's largest economy grew at an annual rate of 2.9%, [*]()
The world's largest economy grew at an annual rate of 2.9%, according to the Commerce Department.

Determining how sentences should collapse could be done by hand, or determined by some rule-based algorithm operating over a dependency parse - it's probably much more complicated than I'm making it out to be, though!

I'd been thinking about how to represent sentence structure for a while and the mutable sentences just clicked.

**Comment by lizadaly** [comment]
Cool, I get it. Yeah, I think the only way you could do that with the library as-is would be a really messy mix of Lists and Maps that would be worse than just writing it by hand. The real limitation of Lists here is twofold:

* They expect the whole expansion to be linkable, so you can't make just one word linked in an expression. That's obviously limiting. 
* There's no way to leave part of an expansion behind as you progress through the sequence; they're replaced entirely. So implementing the above would be really repetitive for the author.

I've also been thinking of accepting a Tracery grammar—maybe via a different component—that could still trigger the event model with each selection, but would be a much more compact and expressive way to author them. Do you think that would work for this?

**Comment by michelleful** [comment]
I'm not super familiar with Tracery, but I guess the question here is what would be an efficient and readable representation.

If I start from first principles and ignore the current structure of things in either windrift or Tracery, the first thing I'd come up with is this:

```
[
  [The (world's largest) economy]
  [grew
     (at [an (annual) rate] of 2.9%) 
  ]
  (according to the Commerce Department)
]
```
where:

1. text in square brackets shows up on screen
2. if they contain a round bracket as an immediate child they're clickable
3. round brackets are converted to square brackets when their immediate parent is clicked

This does give us "an rate" but that's a problem with most text replacement systems and could possibly be dealt with in post-processing (happily my main use-case for this is Mandarin Chinese which, thankfully, has few such problems). 

Going back to windrift, I was looking at examples like this:

```
<List expansions={["card", 'card, which you flip over and read...']}/>
```

and thought that something like the above could be written:

```
<List expansions={["The economy", "The world's largest economy"]}/>
<List expansions={["grew", "grew to 
    <List expansions={["a rate", "an annual rate"]}
    of 2.9%"]}/>
<List expansions={["*", "according to the Commerce Department"]}/>
```

Not sure if this is very elegant - I have to think about it a bit more and look at Tracery in greater detail to give you a better answer.

**Comment by lizadaly** [comment]
I like the way your grammar is focused on revealing text in-place, at any point, rather than the linear way that Lists are implemented. Tracery is probably better used as an alternate syntax for Maps.

I'm up for figuring out how to implement this; I can see that being useful for all kinds of expressions.

**Comment by michelleful** [comment]
Would be happy to work on it together if you think it'll be useful!

**Comment by lizadaly** [comment]
Do you think you could write a quick parser for that representation (Python's fine, I'll port it) and I can integrate it into the framework and try it out? I don't need anything but an in-memory representation of the parse tree; I'll handle rendering that to HTML.

**Comment by lizadaly** [comment]
Moved the old issue to #14

**Comment by michelleful** [comment]
I've put a simple parser [in this gist](https://gist.github.com/michelleful/39bdeaa7bea14bda5306fc0dc41f7c16). Let me know if anything needs clarification; it's lightly tested so I may have missed some details.

**Comment by lizadaly** [comment]
🎉 Awright! I'll work on the port this week.

**Comment by lizadaly** [comment]
Ugh, sorry for the commit spam above, I didn't realize github.com would preserve those after a rebase. Anyway, I finally have something working:

https://lizadaly.github.io/windrift/examples/nested-list/index.html

The unfolding logic falls out a bit differently than you described, since there's no special-case for a trailing hidden node. (I also didn't try to solve a/an nor is this really integrated into the event model yet.)

`*` doesn't feel right to me, especially in a narrative context, so I'm wondering about an additional grammar element, like `{this}`, where the node is hidden but an ellipsis is displayed, which disappears when clicked. The specific characters that are replaced could be overridden in a parameter to the component.

So, using the above example:

```
<NestedList expansions={[
  [The (world's largest) economy]
  [grew
     (at [an (annual) rate] of 2.9%) 
  ]
  {according to the Commerce Department}
]} tag="tag" />
```

Becomes, initially: <a href="">The economy</a> <a href="">grew</a> <a href="">...</a> 

but clicking on `...` replaces:

<a href="">The economy</a> <a href="">grew</a> according to the Commerce Department

To substitute something else for '...', pass a property:

```
<NestedList expansions={[
  [hello]
  {world}
]} tag="tag" ellipsis="*" />
```

Would that work for your idea?

**Comment by michelleful** [comment]
Thank you for putting all this together! The demo works really well. (Although it seems to be missing the default ellipses?) However, I've been having trouble reproducing it independently. I tried sticking some of the code snippets above into the windrift-starter-project but it then doesn't compile (skips the entire chapter). 

I tried looking at the code in the example as a reference, but it currently seems to have just the compiled code in `story.js` and not the "raw" React code, unless I'm missing something.

**Comment by lizadaly** [comment]
I didn't make it clear, but I hadn't implemented the ellipsis feature yet, I was just speculating about it. But now I did!

Demo updated: https://lizadaly.github.io/windrift/examples/nested-list/index.html

Uncompiled example code: 
https://github.com/lizadaly/windrift/blob/044ff435a4fcbb03d8bbf8bbb6c38f9901105a7f/examples/nested-list/example.js

**Comment by lizadaly** [comment]
Closing this out because it ended up not going anywhere, but it was fun to put the example together!
