### ISSUE TITLE
local server index 404s

### ISSUE THREAD

**Issue by makeartandgames** [lizadaly/windrift#172]
Thank you for your work on this project! I was very taken with its application in [The Ballroom](https://ifdb.org/viewgame?id=xqhwputtalxc9jq2).

When I run `npm run dev` or `npm run start` and go to localhost:3000 I get a 404 page with the following error logged in the browser's javascript console:
```javascript
on-demand-entries-utils.js:37 GET http://localhost:3000/ 404 (Not Found)
(anonymous) @ on-demand-entries-utils.js:37
handleMessage @ eventsource.js:34
```

When I go to http://localhost:3000/stone-harbor/   the story loads correctly. It took me a good bit to figure out that the pages were really being built and what the correct url was, so some visible hint in the readme might be useful.

**Comment by lizadaly** [comment]
Thank you so much for filing this—this was a TODO that I hadn't made an issue for yet so I appreciate that it exists now! I'm intending to make this page a pointer to the manual and to include a component that will list all installed stories that an author could re-use (though I think most people will deploy individual stories separately). 

Really appreciate you trying it out and verifying that the install works!

**Comment by lizadaly** [comment]
Added a page; thanks for the report!
